[package]
name = "spotify-lyrics-api"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = "0.4.44"
serde = { version = "1.0.163", features = ["derive"] }
serde-aux = { version = "4.2.0", default-features = false }
serde_json = "1.0.96"
